name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      # - uses: docker/setup-qemu-action@v2
      # - uses: docker/setup-buildx-action@v2

      #- name: Cache Docker layers
      #  uses: actions/cache@v3
      #  with:
      #    path: /tmp/.buildx-cache
      #    key: ${{ runner.os }}-${{ matrix.component }}-buildx-${{ github.sha }}
      #    restore-keys: |
      #      ${{ runner.os }}-${{ matrix.component }}-buildx-

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          chmod +x ./build.sh
          git clone -b current --single-branch https://github.com/vyos/vyos-build
          docker run --rm --privileged -v $(pwd)/vyos-build:/vyos -v $(pwd)/build.sh:/build.sh -w /vyos vyos/vyos-build:current bash /build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: vyos-iso-${{ matrix.arch }}
          path: vyos-build/build/live-image-${{ matrix.arch }}.hybrid.iso

      #- name: Build
      #  uses: docker/build-push-action@v3
      #  with:
      #    file: Dockerfile.gh-actions
      #    context: ctx
      #    platforms: linux/amd64,linux/arm64,linux/arm/v7
      #    build-args: COMPONENT=${{ matrix.component }}
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
      #    cache-from: type=local,src=/tmp/.buildx-cache
      #    cache-to: type=local,dest=/tmp/.buildx-cache-new

      #- name: Move cache
      #  run: |
      #    rm -rf /tmp/.buildx-cache
      #    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
